copy "\\rifsserver\scripts\autowin\Windows\главное меню\1С Предприятие.lnk" "c:\windows\главное меню\1С Предприятие.lnk"
copy "\\rifsserver\scripts\autowin\Windows\главное меню\BRED2.EXE.lnk" "c:\windows\главное меню\BRED2.EXE.lnk"
copy "\\rifsserver\scripts\autowin\Windows\главное меню\Remote Administrator viewer.lnk" "c:\windows\главное меню\Remote Administrator viewer.lnk"
copy "\\rifsserver\scripts\autowin\Windows\главное меню\Total Commander 32.lnk" "c:\windows\главное меню\Total Commander 32.lnk"
copy "\\rifsserver\scripts\autowin\Windows\главное меню\Ultra Edit.lnk" "c:\windows\главное меню\Ultra Edit.lnk"
copy "\\rifsserver\scripts\autowin\Windows\главное меню\WINCMD32.lnk" "c:\windows\главное меню\WINCMD32.lnk"
copy "\\rifsserver\scripts\autowin\Windows\главное меню\Программы\Проводник.lnk" "c:\windows\главное меню\Программы\Проводник.lnk"
copy "\\rifsserver\scripts\autowin\Windows\главное меню\Программы\1C Предприятие 7.7\1С Предприятие Монопольно.lnk" "c:\windows\главное меню\Программы\1C Предприятие 7.7\1С Предприятие Монопольно.lnk"
copy "\\rifsserver\scripts\autowin\Windows\главное меню\Программы\1C Предприятие 7.7\1С Предприятие.lnk" "c:\windows\главное меню\Программы\1C Предприятие 7.7\1С Предприятие.lnk"
copy "\\rifsserver\scripts\autowin\Windows\главное меню\Программы\1C Предприятие 7.7\Readme - Дополнительная информация.lnk" "c:\windows\главное меню\Программы\1C Предприятие 7.7\Readme - Дополнительная информация.lnk"
copy "\\rifsserver\scripts\autowin\Windows\главное меню\Программы\1C Предприятие 7.7\Конфигуратор.lnk" "c:\windows\главное меню\Программы\1C Предприятие 7.7\Конфигуратор.lnk"
copy "\\rifsserver\scripts\autowin\Windows\главное меню\Программы\1C Предприятие 7.7\Монитор пользователей.lnk" "c:\windows\главное меню\Программы\1C Предприятие 7.7\Монитор пользователей.lnk"
copy "\\rifsserver\scripts\autowin\Windows\главное меню\Программы\1C Предприятие 7.7\Отладчик.lnk" "c:\windows\главное меню\Программы\1C Предприятие 7.7\Отладчик.lnk"
copy "\\rifsserver\scripts\autowin\Windows\главное меню\Программы\1C Предприятие 7.7\Переход с версии 7.5.lnk" "c:\windows\главное меню\Программы\1C Предприятие 7.7\Переход с версии 7.5.lnk"
copy "\\rifsserver\scripts\autowin\Windows\главное меню\Программы\1C Предприятие 7.7\Сервер защиты.lnk" "c:\windows\главное меню\Программы\1C Предприятие 7.7\Сервер защиты.lnk"
copy "\\rifsserver\scripts\autowin\Windows\главное меню\Программы\1C Предприятие 7.7\Удаление драйвера защиты.lnk" "c:\windows\главное меню\Программы\1C Предприятие 7.7\Удаление драйвера защиты.lnk"
copy "\\rifsserver\scripts\autowin\Windows\главное меню\Программы\1C Предприятие 7.7\Установка драйвера защиты.lnk" "c:\windows\главное меню\Программы\1C Предприятие 7.7\Установка драйвера защиты.lnk"
copy "\\rifsserver\scripts\autowin\Windows\главное меню\Программы\Citrix ICA Client\Citrix Program Neighborhood.lnk" "c:\windows\главное меню\Программы\Citrix ICA Client\Citrix Program Neighborhood.lnk"
copy "\\rifsserver\scripts\autowin\Windows\главное меню\Программы\Клиент служб терминалов\Диспетчер клиентских подключений.lnk" "c:\windows\главное меню\Программы\Клиент служб терминалов\Диспетчер клиентских подключений.lnk"
copy "\\rifsserver\scripts\autowin\Windows\главное меню\Программы\Клиент служб терминалов\Клиент служб терминалов.lnk" "c:\windows\главное меню\Программы\Клиент служб терминалов\Клиент служб терминалов.lnk"
copy "\\rifsserver\scripts\autowin\Windows\главное меню\Программы\Клиент служб терминалов\Отмена установки.lnk" "c:\windows\главное меню\Программы\Клиент служб терминалов\Отмена установки.lnk"
copy "\\rifsserver\scripts\autowin\Windows\главное меню\Утилиты\BlitzHTML.exe.lnk" "c:\windows\главное меню\Утилиты\BlitzHTML.exe.lnk"
copy "\\rifsserver\scripts\autowin\Windows\главное меню\Утилиты\dllviewer.exe.lnk" "c:\windows\главное меню\Утилиты\dllviewer.exe.lnk"
copy "\\rifsserver\scripts\autowin\Windows\главное меню\Утилиты\Filemon.exe.lnk" "c:\windows\главное меню\Утилиты\Filemon.exe.lnk"
copy "\\rifsserver\scripts\autowin\Windows\главное меню\Утилиты\FreeMem.exe.lnk" "c:\windows\главное меню\Утилиты\FreeMem.exe.lnk"
copy "\\rifsserver\scripts\autowin\Windows\главное меню\Утилиты\hren.exe.lnk" "c:\windows\главное меню\Утилиты\hren.exe.lnk"
copy "\\rifsserver\scripts\autowin\Windows\главное меню\Утилиты\HTMLChanger.exe.lnk" "c:\windows\главное меню\Утилиты\HTMLChanger.exe.lnk"
copy "\\rifsserver\scripts\autowin\Windows\главное меню\Утилиты\PrcView.exe.lnk" "c:\windows\главное меню\Утилиты\PrcView.exe.lnk"
copy "\\rifsserver\scripts\autowin\Windows\главное меню\Утилиты\Regmon.exe.lnk" "c:\windows\главное меню\Утилиты\Regmon.exe.lnk"
copy "\\rifsserver\scripts\autowin\Windows\главное меню\Утилиты\REGVIEW.EXE.pif" "c:\windows\главное меню\Утилиты\REGVIEW.EXE.pif"
copy "\\rifsserver\scripts\autowin\Windows\главное меню\Утилиты\ResHacker.exe.lnk" "c:\windows\главное меню\Утилиты\ResHacker.exe.lnk"
copy "\\rifsserver\scripts\autowin\Windows\главное меню\Утилиты\Scanner.exe.lnk" "c:\windows\главное меню\Утилиты\Scanner.exe.lnk"
copy "\\rifsserver\scripts\autowin\Windows\главное меню\Утилиты\Wclock32.exe.lnk" "c:\windows\главное меню\Утилиты\Wclock32.exe.lnk"
pause
